name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Identity Check
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create JSON File from Secret
        run: |
          echo '${{ secrets.FIREBASE }}' > firebase_credentials.json
        shell: bash

      - name: Create .env File from Secret
        run: |
          echo "${{ secrets.ENV_VAR }}" > .env
        shell: bash

      - name: Execute Make All
        run: make all
