name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Identity Check
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download firebase.json from S3
        working-directory: ./
        run: |
          aws s3 cp s3://foodfridge-firebase/firebase_credentials.json .
          aws s3 cp s3://foodfridge-firebase/secrets.txt ./.env

      - name: Deploy
        working-directory: ./
        run: make all-aws
